// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udjdtvuyvzsxrujdiwxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkamR0dnV5dnpzeHJ1amRpd3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMDY1NzAsImV4cCI6MjA1MTU4MjU3MH0.xFFDm_gJZ7Qgds2Ilm0MsZTRcs42hJ14Wf8bu1JZaN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
